default:
  tags: 
    - gitlab-runner-test

stages:
  - external_alb_create

Ext_ALB:
  stage: external_alb_create
  script:
    - terraform init
    - terraform plan
    - terraform apply --auto-approve
