default:
  tags: 
    - gitlab-runner-test

stages:
   - ecs_cluster_build

ECS_Cluster_Build:
  stage: ecs_cluster_build
  script:
    - terraform init
    - terraform plan
    - terraform apply --auto-approve
